# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNativeStarter' do
 
 # Pods for drivezyApp
 pod 'Firebase/Core', '~> 5.3.0'
 pod 'Firebase/Analytics', '~> 5.3.0'
 pod 'Firebase/Auth', '~> 5.3.0'
 pod 'Firebase/Firestore', '~> 5.3.0'
 pod 'Firebase/Messaging', '~> 5.3.0'
 pod 'Firebase/Database', '~> 5.3.0'
 pod 'Fabric', '~> 1.7.5'
 pod 'Crashlytics', '~> 3.10.4'
 pod 'Firebase/Invites', '~> 5.3.0'
 pod 'Firebase/RemoteConfig', '~> 5.3.0'
 pod 'Firebase/Storage', '~> 5.3.0'
 pod 'Firebase/DynamicLinks', '~> 5.3.0'
 pod 'Firebase/Performance', '~> 5.3.0'
 pod 'GoogleSignIn'
end
